### ISSUE TITLE
Is the model of the IBM ISA 3D bracket available?

### ISSUE THREAD

**Issue by smartroad** [dekuNukem/PicoRC#1]
As title says, is the bracket 3D file available somewhere? Need to print a new one (don't ask why lol)

**Comment by dekuNukem** [comment]
yes i designed it myself and just didn’t upload it. I’ll add it to the repo tomorrow!

**Comment by dekuNukem** [comment]
https://github.com/dekuNukem/PicoRC/blob/master/pcb/ibmpc/isa%20bracket.stl

**Comment by smartroad** [comment]
Awesome thank you!
